repos:
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.8
    hooks:
      - id: ripsecrets

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
